//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace Substrate.NetApi.Generated.Model.pallet_dca.pallet
{
    
    
    public enum Error
    {
        
        ScheduleNotFound = 0,
        
        MinTradeAmountNotReached = 1,
        
        Forbidden = 2,
        
        BlockNumberIsNotInFuture = 3,
        
        PriceUnstable = 4,
        
        CalculatingPriceError = 5,
        
        TotalAmountIsSmallerThanMinBudget = 6,
        
        BudgetTooLow = 7,
        
        NoFreeBlockFound = 8,
        
        ManuallyTerminated = 9,
        
        MaxRetryReached = 10,
        
        TradeLimitReached = 11,
        
        SlippageLimitReached = 12,
        
        RouteNotSpecified = 13,
        
        NoParentHashFound = 14,
        
        InvalidState = 15,
    }
    
    /// <summary>
    /// >> 511 - Variant[pallet_dca.pallet.Error]
    /// 
    ///			Custom [dispatch errors](https://docs.substrate.io/main-docs/build/events-errors/)
    ///			of this pallet.
    ///			
    /// </summary>
    public sealed class EnumError : BaseEnum<Error>
    {
    }
}
