//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace AjunaExample.NetApiExt.Generated.Model.pallet_sudo.pallet
{
    
    
    public enum Error
    {
        
        RequireSudo = 0,
    }
    
    /// <summary>
    /// >> 118 - Variant[pallet_sudo.pallet.Error]
    /// Error for the Sudo pallet
    /// </summary>
    public sealed class EnumError : BaseEnum<Error>
    {
    }
}
