//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Attributes;
using Substrate.NetApi.Model.Types.Base;
using Substrate.NetApi.Model.Types.Metadata.V14;
using System.Collections.Generic;


namespace Hydration.NetApi.Generated.Model.pallet_staking.types
{
    
    
    /// <summary>
    /// >> 523 - Composite[pallet_staking.types.StakingData]
    /// </summary>
    [SubstrateNodeType(TypeDefEnum.Composite)]
    public sealed class StakingData : BaseType
    {
        
        /// <summary>
        /// >> total_stake
        /// </summary>
        public Substrate.NetApi.Model.Types.Primitive.U128 TotalStake { get; set; }
        /// <summary>
        /// >> accumulated_reward_per_stake
        /// </summary>
        public Hydration.NetApi.Generated.Model.sp_arithmetic.fixed_point.FixedU128 AccumulatedRewardPerStake { get; set; }
        /// <summary>
        /// >> pot_reserved_balance
        /// </summary>
        public Substrate.NetApi.Model.Types.Primitive.U128 PotReservedBalance { get; set; }
        
        /// <inheritdoc/>
        public override string TypeName()
        {
            return "StakingData";
        }
        
        /// <inheritdoc/>
        public override byte[] Encode()
        {
            var result = new List<byte>();
            result.AddRange(TotalStake.Encode());
            result.AddRange(AccumulatedRewardPerStake.Encode());
            result.AddRange(PotReservedBalance.Encode());
            return result.ToArray();
        }
        
        /// <inheritdoc/>
        public override void Decode(byte[] byteArray, ref int p)
        {
            var start = p;
            TotalStake = new Substrate.NetApi.Model.Types.Primitive.U128();
            TotalStake.Decode(byteArray, ref p);
            AccumulatedRewardPerStake = new Hydration.NetApi.Generated.Model.sp_arithmetic.fixed_point.FixedU128();
            AccumulatedRewardPerStake.Decode(byteArray, ref p);
            PotReservedBalance = new Substrate.NetApi.Model.Types.Primitive.U128();
            PotReservedBalance.Decode(byteArray, ref p);
            var bytesLength = p - start;
            TypeSize = bytesLength;
            Bytes = new byte[bytesLength];
            System.Array.Copy(byteArray, start, Bytes, 0, bytesLength);
        }
    }
}
