//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace Bifrost.NetApi.Generated.Model.pallet_identity.simple
{
    
    
    /// <summary>
    /// >> IdentityField
    /// </summary>
    public enum IdentityField
    {
        
        /// <summary>
        /// >> Display
        /// </summary>
        Display = 0,
        
        /// <summary>
        /// >> Legal
        /// </summary>
        Legal = 1,
        
        /// <summary>
        /// >> Web
        /// </summary>
        Web = 2,
        
        /// <summary>
        /// >> Riot
        /// </summary>
        Riot = 3,
        
        /// <summary>
        /// >> Email
        /// </summary>
        Email = 4,
        
        /// <summary>
        /// >> PgpFingerprint
        /// </summary>
        PgpFingerprint = 5,
        
        /// <summary>
        /// >> Image
        /// </summary>
        Image = 6,
        
        /// <summary>
        /// >> Twitter
        /// </summary>
        Twitter = 7,
    }
    
    /// <summary>
    /// >> 241 - Variant[pallet_identity.simple.IdentityField]
    /// </summary>
    public sealed class EnumIdentityField : BaseEnum<IdentityField>
    {
    }
}
