//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace Hydration.NetApi.Generated.Model.orml_unknown_tokens.module
{
    
    
    /// <summary>
    /// >> Event
    /// The `Event` enum of this pallet
    /// </summary>
    public enum Event
    {
        
        /// <summary>
        /// >> Deposited
        /// Deposit success.
        /// </summary>
        Deposited = 0,
        
        /// <summary>
        /// >> Withdrawn
        /// Withdraw success.
        /// </summary>
        Withdrawn = 1,
    }
    
    /// <summary>
    /// >> 202 - Variant[orml_unknown_tokens.module.Event]
    /// The `Event` enum of this pallet
    /// </summary>
    public sealed class EnumEvent : BaseEnumExt<Event, BaseTuple<Hydration.NetApi.Generated.Model.staging_xcm.v3.multiasset.MultiAsset, Hydration.NetApi.Generated.Model.staging_xcm.v3.multilocation.MultiLocation>, BaseTuple<Hydration.NetApi.Generated.Model.staging_xcm.v3.multiasset.MultiAsset, Hydration.NetApi.Generated.Model.staging_xcm.v3.multilocation.MultiLocation>>
    {
    }
}
