//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace Substrate.NetApi.Generated.Model.pallet_xcm.pallet
{
    
    
    public enum Origin
    {
        
        Xcm = 0,
        
        Response = 1,
    }
    
    /// <summary>
    /// >> 261 - Variant[pallet_xcm.pallet.Origin]
    /// </summary>
    public sealed class EnumOrigin : BaseEnumExt<Origin, Substrate.NetApi.Generated.Model.xcm.v1.multilocation.MultiLocation, Substrate.NetApi.Generated.Model.xcm.v1.multilocation.MultiLocation>
    {
    }
}
