//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace Substrate.NetApi.Generated.Model.polkadot_primitives.v2
{
    
    
    public enum UpgradeRestriction
    {
        
        Present = 0,
    }
    
    /// <summary>
    /// >> 677 - Variant[polkadot_primitives.v2.UpgradeRestriction]
    /// </summary>
    public sealed class EnumUpgradeRestriction : BaseEnum<UpgradeRestriction>
    {
    }
}
