//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace PlutoWallet.NetApiExt.Generated.Model.pallet_nomination_pools
{
    
    
    public enum BondExtra
    {
        
        FreeBalance = 0,
        
        Rewards = 1,
    }
    
    /// <summary>
    /// >> 370 - Variant[pallet_nomination_pools.BondExtra]
    /// </summary>
    public sealed class EnumBondExtra : BaseEnumExt<BondExtra, Ajuna.NetApi.Model.Types.Primitive.U128, BaseVoid>
    {
    }
}
