//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace PlutoWallet.NetApiExt.Generated.Model.pallet_democracy.vote_threshold
{
    
    
    public enum VoteThreshold
    {
        
        SuperMajorityApprove = 0,
        
        SuperMajorityAgainst = 1,
        
        SimpleMajority = 2,
    }
    
    /// <summary>
    /// >> 62 - Variant[pallet_democracy.vote_threshold.VoteThreshold]
    /// </summary>
    public sealed class EnumVoteThreshold : BaseEnum<VoteThreshold>
    {
    }
}
