//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace PolkadotAssetHub.NetApi.Generated.Model.cumulus_pallet_xcmp_queue.pallet
{
    
    
    /// <summary>
    /// >> Event
    /// The `Event` enum of this pallet
    /// </summary>
    public enum Event
    {
        
        /// <summary>
        /// >> XcmpMessageSent
        /// An HRMP message was sent to a sibling parachain.
        /// </summary>
        XcmpMessageSent = 0,
    }
    
    /// <summary>
    /// >> 50 - Variant[cumulus_pallet_xcmp_queue.pallet.Event]
    /// The `Event` enum of this pallet
    /// </summary>
    public sealed class EnumEvent : BaseEnumExt<Event, PolkadotAssetHub.NetApi.Generated.Types.Base.Arr32U8>
    {
    }
}
