//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Attributes;
using Substrate.NetApi.Model.Types.Base;
using Substrate.NetApi.Model.Types.Metadata.V14;
using System.Collections.Generic;


namespace Substrate.NetApi.Generated.Model.polkadot_primitives.v2
{
    
    
    /// <summary>
    /// >> 379 - Composite[polkadot_primitives.v2.InherentData]
    /// </summary>
    [SubstrateNodeType(TypeDefEnum.Composite)]
    public sealed class InherentData : BaseType
    {
        
        /// <summary>
        /// >> bitfields
        /// </summary>
        private Substrate.NetApi.Model.Types.Base.BaseVec<Substrate.NetApi.Generated.Model.polkadot_primitives.v2.signed.UncheckedSigned> _bitfields;
        
        /// <summary>
        /// >> backed_candidates
        /// </summary>
        private Substrate.NetApi.Model.Types.Base.BaseVec<Substrate.NetApi.Generated.Model.polkadot_primitives.v2.BackedCandidate> _backedCandidates;
        
        /// <summary>
        /// >> disputes
        /// </summary>
        private Substrate.NetApi.Model.Types.Base.BaseVec<Substrate.NetApi.Generated.Model.polkadot_primitives.v2.DisputeStatementSet> _disputes;
        
        /// <summary>
        /// >> parent_header
        /// </summary>
        private Substrate.NetApi.Generated.Model.sp_runtime.generic.header.Header _parentHeader;
        
        public Substrate.NetApi.Model.Types.Base.BaseVec<Substrate.NetApi.Generated.Model.polkadot_primitives.v2.signed.UncheckedSigned> Bitfields
        {
            get
            {
                return this._bitfields;
            }
            set
            {
                this._bitfields = value;
            }
        }
        
        public Substrate.NetApi.Model.Types.Base.BaseVec<Substrate.NetApi.Generated.Model.polkadot_primitives.v2.BackedCandidate> BackedCandidates
        {
            get
            {
                return this._backedCandidates;
            }
            set
            {
                this._backedCandidates = value;
            }
        }
        
        public Substrate.NetApi.Model.Types.Base.BaseVec<Substrate.NetApi.Generated.Model.polkadot_primitives.v2.DisputeStatementSet> Disputes
        {
            get
            {
                return this._disputes;
            }
            set
            {
                this._disputes = value;
            }
        }
        
        public Substrate.NetApi.Generated.Model.sp_runtime.generic.header.Header ParentHeader
        {
            get
            {
                return this._parentHeader;
            }
            set
            {
                this._parentHeader = value;
            }
        }
        
        public override string TypeName()
        {
            return "InherentData";
        }
        
        public override byte[] Encode()
        {
            var result = new List<byte>();
            result.AddRange(Bitfields.Encode());
            result.AddRange(BackedCandidates.Encode());
            result.AddRange(Disputes.Encode());
            result.AddRange(ParentHeader.Encode());
            return result.ToArray();
        }
        
        public override void Decode(byte[] byteArray, ref int p)
        {
            var start = p;
            Bitfields = new Substrate.NetApi.Model.Types.Base.BaseVec<Substrate.NetApi.Generated.Model.polkadot_primitives.v2.signed.UncheckedSigned>();
            Bitfields.Decode(byteArray, ref p);
            BackedCandidates = new Substrate.NetApi.Model.Types.Base.BaseVec<Substrate.NetApi.Generated.Model.polkadot_primitives.v2.BackedCandidate>();
            BackedCandidates.Decode(byteArray, ref p);
            Disputes = new Substrate.NetApi.Model.Types.Base.BaseVec<Substrate.NetApi.Generated.Model.polkadot_primitives.v2.DisputeStatementSet>();
            Disputes.Decode(byteArray, ref p);
            ParentHeader = new Substrate.NetApi.Generated.Model.sp_runtime.generic.header.Header();
            ParentHeader.Decode(byteArray, ref p);
            TypeSize = p - start;
        }
    }
}
