//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace Hydration.NetApi.Generated.Model.pallet_liquidity_mining.pallet
{
    
    
    /// <summary>
    /// >> InconsistentStateError
    /// </summary>
    public enum InconsistentStateError
    {
        
        /// <summary>
        /// >> YieldFarmNotFound
        /// </summary>
        YieldFarmNotFound = 0,
        
        /// <summary>
        /// >> GlobalFarmNotFound
        /// </summary>
        GlobalFarmNotFound = 1,
        
        /// <summary>
        /// >> LiquidityIsNotActive
        /// </summary>
        LiquidityIsNotActive = 2,
        
        /// <summary>
        /// >> GlobalFarmIsNotActive
        /// </summary>
        GlobalFarmIsNotActive = 3,
        
        /// <summary>
        /// >> DepositNotFound
        /// </summary>
        DepositNotFound = 4,
        
        /// <summary>
        /// >> InvalidPeriod
        /// </summary>
        InvalidPeriod = 5,
        
        /// <summary>
        /// >> NotEnoughRewardsInYieldFarm
        /// </summary>
        NotEnoughRewardsInYieldFarm = 6,
        
        /// <summary>
        /// >> InvalidLiveYielFarmsCount
        /// </summary>
        InvalidLiveYielFarmsCount = 7,
        
        /// <summary>
        /// >> InvalidTotalYieldFarmsCount
        /// </summary>
        InvalidTotalYieldFarmsCount = 8,
        
        /// <summary>
        /// >> InvalidYieldFarmEntriesCount
        /// </summary>
        InvalidYieldFarmEntriesCount = 9,
        
        /// <summary>
        /// >> InvalidTotalShares
        /// </summary>
        InvalidTotalShares = 10,
        
        /// <summary>
        /// >> InvalidValuedShares
        /// </summary>
        InvalidValuedShares = 11,
        
        /// <summary>
        /// >> InvalidTotalSharesZ
        /// </summary>
        InvalidTotalSharesZ = 12,
        
        /// <summary>
        /// >> InvalidPaidAccumulatedRewards
        /// </summary>
        InvalidPaidAccumulatedRewards = 13,
        
        /// <summary>
        /// >> InvalidFarmId
        /// </summary>
        InvalidFarmId = 14,
        
        /// <summary>
        /// >> InvalidLoyaltyMultiplier
        /// </summary>
        InvalidLoyaltyMultiplier = 15,
    }
    
    /// <summary>
    /// >> 510 - Variant[pallet_liquidity_mining.pallet.InconsistentStateError]
    /// </summary>
    public sealed class EnumInconsistentStateError : BaseEnum<InconsistentStateError>
    {
    }
}
