//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Attributes;
using Substrate.NetApi.Model.Types.Base;
using Substrate.NetApi.Model.Types.Metadata.V14;
using System.Collections.Generic;


namespace Substrate.NetApi.Generated.Model.polkadot_runtime_parachains.paras
{
    
    
    /// <summary>
    /// >> 781 - Composite[polkadot_runtime_parachains.paras.ParaGenesisArgs]
    /// </summary>
    [SubstrateNodeType(TypeDefEnum.Composite)]
    public sealed class ParaGenesisArgs : BaseType
    {
        
        /// <summary>
        /// >> genesis_head
        /// </summary>
        public Substrate.NetApi.Generated.Model.polkadot_parachain_primitives.primitives.HeadData GenesisHead { get; set; }
        /// <summary>
        /// >> validation_code
        /// </summary>
        public Substrate.NetApi.Generated.Model.polkadot_parachain_primitives.primitives.ValidationCode ValidationCode { get; set; }
        /// <summary>
        /// >> para_kind
        /// </summary>
        public Substrate.NetApi.Model.Types.Primitive.Bool ParaKind { get; set; }
        
        /// <inheritdoc/>
        public override string TypeName()
        {
            return "ParaGenesisArgs";
        }
        
        /// <inheritdoc/>
        public override byte[] Encode()
        {
            var result = new List<byte>();
            result.AddRange(GenesisHead.Encode());
            result.AddRange(ValidationCode.Encode());
            result.AddRange(ParaKind.Encode());
            return result.ToArray();
        }
        
        /// <inheritdoc/>
        public override void Decode(byte[] byteArray, ref int p)
        {
            var start = p;
            GenesisHead = new Substrate.NetApi.Generated.Model.polkadot_parachain_primitives.primitives.HeadData();
            GenesisHead.Decode(byteArray, ref p);
            ValidationCode = new Substrate.NetApi.Generated.Model.polkadot_parachain_primitives.primitives.ValidationCode();
            ValidationCode.Decode(byteArray, ref p);
            ParaKind = new Substrate.NetApi.Model.Types.Primitive.Bool();
            ParaKind.Decode(byteArray, ref p);
            var bytesLength = p - start;
            TypeSize = bytesLength;
            Bytes = new byte[bytesLength];
            System.Array.Copy(byteArray, start, Bytes, 0, bytesLength);
        }
    }
}
