//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Attributes;
using Substrate.NetApi.Model.Types.Base;
using Substrate.NetApi.Model.Types.Metadata.V14;
using System.Collections.Generic;


namespace Hydration.NetApi.Generated.Model.pallet_ema_oracle.types
{
    
    
    /// <summary>
    /// >> 695 - Composite[pallet_ema_oracle.types.OracleEntry]
    /// </summary>
    [SubstrateNodeType(TypeDefEnum.Composite)]
    public sealed class OracleEntry : BaseType
    {
        
        /// <summary>
        /// >> price
        /// </summary>
        public Hydration.NetApi.Generated.Model.hydra_dx_math.ratio.Ratio Price { get; set; }
        /// <summary>
        /// >> volume
        /// </summary>
        public Hydration.NetApi.Generated.Model.hydradx_traits.oracle.Volume Volume { get; set; }
        /// <summary>
        /// >> liquidity
        /// </summary>
        public Hydration.NetApi.Generated.Model.hydradx_traits.oracle.Liquidity Liquidity { get; set; }
        /// <summary>
        /// >> updated_at
        /// </summary>
        public Substrate.NetApi.Model.Types.Primitive.U32 UpdatedAt { get; set; }
        
        /// <inheritdoc/>
        public override string TypeName()
        {
            return "OracleEntry";
        }
        
        /// <inheritdoc/>
        public override byte[] Encode()
        {
            var result = new List<byte>();
            result.AddRange(Price.Encode());
            result.AddRange(Volume.Encode());
            result.AddRange(Liquidity.Encode());
            result.AddRange(UpdatedAt.Encode());
            return result.ToArray();
        }
        
        /// <inheritdoc/>
        public override void Decode(byte[] byteArray, ref int p)
        {
            var start = p;
            Price = new Hydration.NetApi.Generated.Model.hydra_dx_math.ratio.Ratio();
            Price.Decode(byteArray, ref p);
            Volume = new Hydration.NetApi.Generated.Model.hydradx_traits.oracle.Volume();
            Volume.Decode(byteArray, ref p);
            Liquidity = new Hydration.NetApi.Generated.Model.hydradx_traits.oracle.Liquidity();
            Liquidity.Decode(byteArray, ref p);
            UpdatedAt = new Substrate.NetApi.Model.Types.Primitive.U32();
            UpdatedAt.Decode(byteArray, ref p);
            var bytesLength = p - start;
            TypeSize = bytesLength;
            Bytes = new byte[bytesLength];
            System.Array.Copy(byteArray, start, Bytes, 0, bytesLength);
        }
    }
}
