//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace Substrate.NetApi.Generated.Model.pallet_asset_rate.pallet
{
    
    
    /// <summary>
    /// >> Error
    /// The `Error` enum of this pallet.
    /// </summary>
    public enum Error
    {
        
        /// <summary>
        /// >> UnknownAssetKind
        /// The given asset ID is unknown.
        /// </summary>
        UnknownAssetKind = 0,
        
        /// <summary>
        /// >> AlreadyExists
        /// The given asset ID already has an assigned conversion rate and cannot be re-created.
        /// </summary>
        AlreadyExists = 1,
    }
    
    /// <summary>
    /// >> 850 - Variant[pallet_asset_rate.pallet.Error]
    /// The `Error` enum of this pallet.
    /// </summary>
    public sealed class EnumError : BaseEnum<Error>
    {
    }
}
