//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace Substrate.NetApi.Generated.Model.pallet_bags_list.list
{
    
    
    public enum ListError
    {
        
        Duplicate = 0,
        
        NotHeavier = 1,
        
        NotInSameBag = 2,
        
        NodeNotFound = 3,
    }
    
    /// <summary>
    /// >> 616 - Variant[pallet_bags_list.list.ListError]
    /// </summary>
    public sealed class EnumListError : BaseEnum<ListError>
    {
    }
}
