//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace Bifrost.NetApi.Generated.Model.bifrost_call_switchgear.pallet
{
    
    
    /// <summary>
    /// >> Call
    /// Contains a variant per dispatchable extrinsic that this pallet has.
    /// </summary>
    public enum Call
    {
        
        /// <summary>
        /// >> switchoff_transaction
        /// See [`Pallet::switchoff_transaction`].
        /// </summary>
        switchoff_transaction = 0,
        
        /// <summary>
        /// >> switchon_transaction
        /// See [`Pallet::switchon_transaction`].
        /// </summary>
        switchon_transaction = 1,
        
        /// <summary>
        /// >> disable_transfers
        /// See [`Pallet::disable_transfers`].
        /// </summary>
        disable_transfers = 2,
        
        /// <summary>
        /// >> enable_transfers
        /// See [`Pallet::enable_transfers`].
        /// </summary>
        enable_transfers = 3,
    }
    
    /// <summary>
    /// >> 274 - Variant[bifrost_call_switchgear.pallet.Call]
    /// Contains a variant per dispatchable extrinsic that this pallet has.
    /// </summary>
    public sealed class EnumCall : BaseEnumExt<Call, BaseTuple<Substrate.NetApi.Model.Types.Base.BaseVec<Substrate.NetApi.Model.Types.Primitive.U8>, Substrate.NetApi.Model.Types.Base.BaseVec<Substrate.NetApi.Model.Types.Primitive.U8>>, BaseTuple<Substrate.NetApi.Model.Types.Base.BaseVec<Substrate.NetApi.Model.Types.Primitive.U8>, Substrate.NetApi.Model.Types.Base.BaseVec<Substrate.NetApi.Model.Types.Primitive.U8>>, Bifrost.NetApi.Generated.Model.bifrost_primitives.currency.EnumCurrencyId, Bifrost.NetApi.Generated.Model.bifrost_primitives.currency.EnumCurrencyId>
    {
    }
}
