//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Attributes;
using Substrate.NetApi.Model.Types.Base;
using Substrate.NetApi.Model.Types.Metadata.V14;
using System.Collections.Generic;


namespace PlutoWallet.NetApiExt.Generated.Model.pallet_grandpa
{
    
    
    /// <summary>
    /// >> 516 - Composite[pallet_grandpa.StoredPendingChange]
    /// </summary>
    [SubstrateNodeType(TypeDefEnum.Composite)]
    public sealed class StoredPendingChange : BaseType
    {
        
        /// <summary>
        /// >> scheduled_at
        /// </summary>
        private Substrate.NetApi.Model.Types.Primitive.U32 _scheduledAt;
        
        /// <summary>
        /// >> delay
        /// </summary>
        private Substrate.NetApi.Model.Types.Primitive.U32 _delay;
        
        /// <summary>
        /// >> next_authorities
        /// </summary>
        private PlutoWallet.NetApiExt.Generated.Model.sp_core.bounded.weak_bounded_vec.WeakBoundedVecT4 _nextAuthorities;
        
        /// <summary>
        /// >> forced
        /// </summary>
        private Substrate.NetApi.Model.Types.Base.BaseOpt<Substrate.NetApi.Model.Types.Primitive.U32> _forced;
        
        public Substrate.NetApi.Model.Types.Primitive.U32 ScheduledAt
        {
            get
            {
                return this._scheduledAt;
            }
            set
            {
                this._scheduledAt = value;
            }
        }
        
        public Substrate.NetApi.Model.Types.Primitive.U32 Delay
        {
            get
            {
                return this._delay;
            }
            set
            {
                this._delay = value;
            }
        }
        
        public PlutoWallet.NetApiExt.Generated.Model.sp_core.bounded.weak_bounded_vec.WeakBoundedVecT4 NextAuthorities
        {
            get
            {
                return this._nextAuthorities;
            }
            set
            {
                this._nextAuthorities = value;
            }
        }
        
        public Substrate.NetApi.Model.Types.Base.BaseOpt<Substrate.NetApi.Model.Types.Primitive.U32> Forced
        {
            get
            {
                return this._forced;
            }
            set
            {
                this._forced = value;
            }
        }
        
        public override string TypeName()
        {
            return "StoredPendingChange";
        }
        
        public override byte[] Encode()
        {
            var result = new List<byte>();
            result.AddRange(ScheduledAt.Encode());
            result.AddRange(Delay.Encode());
            result.AddRange(NextAuthorities.Encode());
            result.AddRange(Forced.Encode());
            return result.ToArray();
        }
        
        public override void Decode(byte[] byteArray, ref int p)
        {
            var start = p;
            ScheduledAt = new Substrate.NetApi.Model.Types.Primitive.U32();
            ScheduledAt.Decode(byteArray, ref p);
            Delay = new Substrate.NetApi.Model.Types.Primitive.U32();
            Delay.Decode(byteArray, ref p);
            NextAuthorities = new PlutoWallet.NetApiExt.Generated.Model.sp_core.bounded.weak_bounded_vec.WeakBoundedVecT4();
            NextAuthorities.Decode(byteArray, ref p);
            Forced = new Substrate.NetApi.Model.Types.Base.BaseOpt<Substrate.NetApi.Model.Types.Primitive.U32>();
            Forced.Decode(byteArray, ref p);
            TypeSize = p - start;
        }
    }
}
