//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace Substrate.NetApi.Generated.Model.xcm.v0
{
    
    
    public enum Response
    {
        
        Assets = 0,
    }
    
    /// <summary>
    /// >> 429 - Variant[xcm.v0.Response]
    /// </summary>
    public sealed class EnumResponse : BaseEnumExt<Response, Substrate.NetApi.Model.Types.Base.BaseVec<Substrate.NetApi.Generated.Model.xcm.v0.multi_asset.EnumMultiAsset>>
    {
    }
}
