//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace Bifrost.NetApi.Generated.Model.bifrost_slp.primitives.parachain_staking_primitives
{
    
    
    /// <summary>
    /// >> OneToManyDelegatorStatus
    /// </summary>
    public enum OneToManyDelegatorStatus
    {
        
        /// <summary>
        /// >> Active
        /// </summary>
        Active = 0,
        
        /// <summary>
        /// >> Leaving
        /// </summary>
        Leaving = 1,
    }
    
    /// <summary>
    /// >> 307 - Variant[bifrost_slp.primitives.parachain_staking_primitives.OneToManyDelegatorStatus]
    /// </summary>
    public sealed class EnumOneToManyDelegatorStatus : BaseEnumExt<OneToManyDelegatorStatus, BaseVoid, Bifrost.NetApi.Generated.Model.bifrost_primitives.EnumTimeUnit>
    {
    }
}
