//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace Substrate.NetApi.Generated.Model.pallet_staking.pallet.pallet
{
    
    
    public enum ConfigOp
    {
        
        Noop = 0,
        
        Set = 1,
        
        Remove = 2,
    }
    
    /// <summary>
    /// >> 210 - Variant[pallet_staking.pallet.pallet.ConfigOp]
    /// </summary>
    public sealed class EnumConfigOp : BaseEnumExt<ConfigOp, BaseVoid, Substrate.NetApi.Generated.Model.sp_arithmetic.per_things.Perbill, BaseVoid>
    {
    }
}
