//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Attributes;
using Substrate.NetApi.Model.Types.Base;
using Substrate.NetApi.Model.Types.Metadata.V14;
using System.Collections.Generic;


namespace PlutoWallet.NetApiExt.Generated.Model.sp_session
{
    
    
    /// <summary>
    /// >> 191 - Composite[sp_session.MembershipProof]
    /// </summary>
    [SubstrateNodeType(TypeDefEnum.Composite)]
    public sealed class MembershipProof : BaseType
    {
        
        /// <summary>
        /// >> session
        /// </summary>
        private Substrate.NetApi.Model.Types.Primitive.U32 _session;
        
        /// <summary>
        /// >> trie_nodes
        /// </summary>
        private Substrate.NetApi.Model.Types.Base.BaseVec<Substrate.NetApi.Model.Types.Base.BaseVec<Substrate.NetApi.Model.Types.Primitive.U8>> _trieNodes;
        
        /// <summary>
        /// >> validator_count
        /// </summary>
        private Substrate.NetApi.Model.Types.Primitive.U32 _validatorCount;
        
        public Substrate.NetApi.Model.Types.Primitive.U32 Session
        {
            get
            {
                return this._session;
            }
            set
            {
                this._session = value;
            }
        }
        
        public Substrate.NetApi.Model.Types.Base.BaseVec<Substrate.NetApi.Model.Types.Base.BaseVec<Substrate.NetApi.Model.Types.Primitive.U8>> TrieNodes
        {
            get
            {
                return this._trieNodes;
            }
            set
            {
                this._trieNodes = value;
            }
        }
        
        public Substrate.NetApi.Model.Types.Primitive.U32 ValidatorCount
        {
            get
            {
                return this._validatorCount;
            }
            set
            {
                this._validatorCount = value;
            }
        }
        
        public override string TypeName()
        {
            return "MembershipProof";
        }
        
        public override byte[] Encode()
        {
            var result = new List<byte>();
            result.AddRange(Session.Encode());
            result.AddRange(TrieNodes.Encode());
            result.AddRange(ValidatorCount.Encode());
            return result.ToArray();
        }
        
        public override void Decode(byte[] byteArray, ref int p)
        {
            var start = p;
            Session = new Substrate.NetApi.Model.Types.Primitive.U32();
            Session.Decode(byteArray, ref p);
            TrieNodes = new Substrate.NetApi.Model.Types.Base.BaseVec<Substrate.NetApi.Model.Types.Base.BaseVec<Substrate.NetApi.Model.Types.Primitive.U8>>();
            TrieNodes.Decode(byteArray, ref p);
            ValidatorCount = new Substrate.NetApi.Model.Types.Primitive.U32();
            ValidatorCount.Decode(byteArray, ref p);
            TypeSize = p - start;
        }
    }
}
