//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace Substrate.NetApi.Generated.Model.polkadot_runtime.governance.origins.pallet_custom_origins
{
    
    
    /// <summary>
    /// >> Origin
    /// </summary>
    public enum Origin
    {
        
        /// <summary>
        /// >> StakingAdmin
        /// </summary>
        StakingAdmin = 0,
        
        /// <summary>
        /// >> Treasurer
        /// </summary>
        Treasurer = 1,
        
        /// <summary>
        /// >> FellowshipAdmin
        /// </summary>
        FellowshipAdmin = 2,
        
        /// <summary>
        /// >> GeneralAdmin
        /// </summary>
        GeneralAdmin = 3,
        
        /// <summary>
        /// >> AuctionAdmin
        /// </summary>
        AuctionAdmin = 4,
        
        /// <summary>
        /// >> LeaseAdmin
        /// </summary>
        LeaseAdmin = 5,
        
        /// <summary>
        /// >> ReferendumCanceller
        /// </summary>
        ReferendumCanceller = 6,
        
        /// <summary>
        /// >> ReferendumKiller
        /// </summary>
        ReferendumKiller = 7,
        
        /// <summary>
        /// >> SmallTipper
        /// </summary>
        SmallTipper = 8,
        
        /// <summary>
        /// >> BigTipper
        /// </summary>
        BigTipper = 9,
        
        /// <summary>
        /// >> SmallSpender
        /// </summary>
        SmallSpender = 10,
        
        /// <summary>
        /// >> MediumSpender
        /// </summary>
        MediumSpender = 11,
        
        /// <summary>
        /// >> BigSpender
        /// </summary>
        BigSpender = 12,
        
        /// <summary>
        /// >> WhitelistedCaller
        /// </summary>
        WhitelistedCaller = 13,
        
        /// <summary>
        /// >> WishForChange
        /// </summary>
        WishForChange = 14,
    }
    
    /// <summary>
    /// >> 172 - Variant[polkadot_runtime.governance.origins.pallet_custom_origins.Origin]
    /// </summary>
    public sealed class EnumOrigin : BaseEnum<Origin>
    {
    }
}
