//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace Hydration.NetApi.Generated.Model.pallet_lbp
{
    
    
    /// <summary>
    /// >> WeightCurveType
    /// </summary>
    public enum WeightCurveType
    {
        
        /// <summary>
        /// >> Linear
        /// </summary>
        Linear = 0,
    }
    
    /// <summary>
    /// >> 110 - Variant[pallet_lbp.WeightCurveType]
    /// </summary>
    public sealed class EnumWeightCurveType : BaseEnum<WeightCurveType>
    {
    }
}
