//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace PlutoWallet.NetApiExt.Generated.Model.sp_consensus_babe.digests
{
    
    
    public enum NextConfigDescriptor
    {
        
        V1 = 1,
    }
    
    /// <summary>
    /// >> 192 - Variant[sp_consensus_babe.digests.NextConfigDescriptor]
    /// </summary>
    public sealed class EnumNextConfigDescriptor : BaseEnumExt<NextConfigDescriptor, BaseVoid, BaseTuple<Substrate.NetApi.Model.Types.Base.BaseTuple<Substrate.NetApi.Model.Types.Primitive.U64, Substrate.NetApi.Model.Types.Primitive.U64>, PlutoWallet.NetApiExt.Generated.Model.sp_consensus_babe.EnumAllowedSlots>>
    {
    }
}
