//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace Bifrost.NetApi.Generated.Model.bifrost_slp.primitives
{
    
    
    /// <summary>
    /// >> LedgerUpdateEntry
    /// </summary>
    public enum LedgerUpdateEntry
    {
        
        /// <summary>
        /// >> Substrate
        /// </summary>
        Substrate = 0,
        
        /// <summary>
        /// >> Moonbeam
        /// </summary>
        Moonbeam = 1,
        
        /// <summary>
        /// >> ParachainStaking
        /// </summary>
        ParachainStaking = 2,
    }
    
    /// <summary>
    /// >> 427 - Variant[bifrost_slp.primitives.LedgerUpdateEntry]
    /// </summary>
    public sealed class EnumLedgerUpdateEntry : BaseEnumExt<LedgerUpdateEntry, Bifrost.NetApi.Generated.Model.bifrost_slp.primitives.polkadot_primitives.SubstrateLedgerUpdateEntry, Bifrost.NetApi.Generated.Model.bifrost_slp.primitives.parachain_staking_primitives.ParachainStakingLedgerUpdateEntry, Bifrost.NetApi.Generated.Model.bifrost_slp.primitives.parachain_staking_primitives.ParachainStakingLedgerUpdateEntry>
    {
    }
}
