//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Attributes;
using Substrate.NetApi.Model.Types.Base;
using Substrate.NetApi.Model.Types.Metadata.V14;
using System.Collections.Generic;


namespace Substrate.NetApi.Generated.Model.finality_grandpa
{
    
    
    /// <summary>
    /// >> 219 - Composite[finality_grandpa.EquivocationT1]
    /// </summary>
    [SubstrateNodeType(TypeDefEnum.Composite)]
    public sealed class EquivocationT1 : BaseType
    {
        
        /// <summary>
        /// >> round_number
        /// </summary>
        private Substrate.NetApi.Model.Types.Primitive.U64 _roundNumber;
        
        /// <summary>
        /// >> identity
        /// </summary>
        private Substrate.NetApi.Generated.Model.sp_finality_grandpa.app.Public _identity;
        
        /// <summary>
        /// >> first
        /// </summary>
        private Substrate.NetApi.Model.Types.Base.BaseTuple<Substrate.NetApi.Generated.Model.finality_grandpa.Prevote, Substrate.NetApi.Generated.Model.sp_finality_grandpa.app.Signature> _first;
        
        /// <summary>
        /// >> second
        /// </summary>
        private Substrate.NetApi.Model.Types.Base.BaseTuple<Substrate.NetApi.Generated.Model.finality_grandpa.Prevote, Substrate.NetApi.Generated.Model.sp_finality_grandpa.app.Signature> _second;
        
        public Substrate.NetApi.Model.Types.Primitive.U64 RoundNumber
        {
            get
            {
                return this._roundNumber;
            }
            set
            {
                this._roundNumber = value;
            }
        }
        
        public Substrate.NetApi.Generated.Model.sp_finality_grandpa.app.Public Identity
        {
            get
            {
                return this._identity;
            }
            set
            {
                this._identity = value;
            }
        }
        
        public Substrate.NetApi.Model.Types.Base.BaseTuple<Substrate.NetApi.Generated.Model.finality_grandpa.Prevote, Substrate.NetApi.Generated.Model.sp_finality_grandpa.app.Signature> First
        {
            get
            {
                return this._first;
            }
            set
            {
                this._first = value;
            }
        }
        
        public Substrate.NetApi.Model.Types.Base.BaseTuple<Substrate.NetApi.Generated.Model.finality_grandpa.Prevote, Substrate.NetApi.Generated.Model.sp_finality_grandpa.app.Signature> Second
        {
            get
            {
                return this._second;
            }
            set
            {
                this._second = value;
            }
        }
        
        public override string TypeName()
        {
            return "EquivocationT1";
        }
        
        public override byte[] Encode()
        {
            var result = new List<byte>();
            result.AddRange(RoundNumber.Encode());
            result.AddRange(Identity.Encode());
            result.AddRange(First.Encode());
            result.AddRange(Second.Encode());
            return result.ToArray();
        }
        
        public override void Decode(byte[] byteArray, ref int p)
        {
            var start = p;
            RoundNumber = new Substrate.NetApi.Model.Types.Primitive.U64();
            RoundNumber.Decode(byteArray, ref p);
            Identity = new Substrate.NetApi.Generated.Model.sp_finality_grandpa.app.Public();
            Identity.Decode(byteArray, ref p);
            First = new Substrate.NetApi.Model.Types.Base.BaseTuple<Substrate.NetApi.Generated.Model.finality_grandpa.Prevote, Substrate.NetApi.Generated.Model.sp_finality_grandpa.app.Signature>();
            First.Decode(byteArray, ref p);
            Second = new Substrate.NetApi.Model.Types.Base.BaseTuple<Substrate.NetApi.Generated.Model.finality_grandpa.Prevote, Substrate.NetApi.Generated.Model.sp_finality_grandpa.app.Signature>();
            Second.Decode(byteArray, ref p);
            TypeSize = p - start;
        }
    }
}
