//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace PlutoWallet.NetApiExt.Generated.Model.xcm.v1.multiasset
{
    
    
    public enum WildMultiAsset
    {
        
        All = 0,
        
        AllOf = 1,
    }
    
    /// <summary>
    /// >> 146 - Variant[xcm.v1.multiasset.WildMultiAsset]
    /// </summary>
    public sealed class EnumWildMultiAsset : BaseEnumExt<WildMultiAsset, BaseVoid, BaseTuple<PlutoWallet.NetApiExt.Generated.Model.xcm.v1.multiasset.EnumAssetId, PlutoWallet.NetApiExt.Generated.Model.xcm.v1.multiasset.EnumWildFungibility>>
    {
    }
}
