//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace PlutoWallet.NetApiExt.Generated.Model.pallet_nfts.types
{
    
    
    public enum ItemSetting
    {
        
        Transferable = 1,
        
        UnlockedMetadata = 2,
        
        UnlockedAttributes = 4,
    }
    
    /// <summary>
    /// >> 291 - Variant[pallet_nfts.types.ItemSetting]
    /// </summary>
    public sealed class EnumItemSetting : BaseEnum<ItemSetting>
    {
    }
}
