//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Attributes;
using Substrate.NetApi.Model.Types.Base;
using Substrate.NetApi.Model.Types.Metadata.V14;
using System.Collections.Generic;


namespace Hydration.NetApi.Generated.Model.hydradx_traits.router
{
    
    
    /// <summary>
    /// >> 147 - Composite[hydradx_traits.router.Trade]
    /// </summary>
    [SubstrateNodeType(TypeDefEnum.Composite)]
    public sealed class Trade : BaseType
    {
        
        /// <summary>
        /// >> pool
        /// </summary>
        public Hydration.NetApi.Generated.Model.hydradx_traits.router.EnumPoolType Pool { get; set; }
        /// <summary>
        /// >> asset_in
        /// </summary>
        public Substrate.NetApi.Model.Types.Primitive.U32 AssetIn { get; set; }
        /// <summary>
        /// >> asset_out
        /// </summary>
        public Substrate.NetApi.Model.Types.Primitive.U32 AssetOut { get; set; }
        
        /// <inheritdoc/>
        public override string TypeName()
        {
            return "Trade";
        }
        
        /// <inheritdoc/>
        public override byte[] Encode()
        {
            var result = new List<byte>();
            result.AddRange(Pool.Encode());
            result.AddRange(AssetIn.Encode());
            result.AddRange(AssetOut.Encode());
            return result.ToArray();
        }
        
        /// <inheritdoc/>
        public override void Decode(byte[] byteArray, ref int p)
        {
            var start = p;
            Pool = new Hydration.NetApi.Generated.Model.hydradx_traits.router.EnumPoolType();
            Pool.Decode(byteArray, ref p);
            AssetIn = new Substrate.NetApi.Model.Types.Primitive.U32();
            AssetIn.Decode(byteArray, ref p);
            AssetOut = new Substrate.NetApi.Model.Types.Primitive.U32();
            AssetOut.Decode(byteArray, ref p);
            var bytesLength = p - start;
            TypeSize = bytesLength;
            Bytes = new byte[bytesLength];
            System.Array.Copy(byteArray, start, Bytes, 0, bytesLength);
        }
    }
}
