//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace Substrate.NetApi.Generated.Model.pallet_asset_registry.pallet
{
    
    
    public enum Error
    {
        
        NoIdAvailable = 0,
        
        AssetNotFound = 1,
        
        TooLong = 2,
        
        AssetNotRegistered = 3,
        
        AssetAlreadyRegistered = 4,
        
        InvalidSharedAssetLen = 5,
        
        CannotUpdateLocation = 6,
        
        NotInReservedRange = 7,
        
        LocationAlreadyRegistered = 8,
    }
    
    /// <summary>
    /// >> 429 - Variant[pallet_asset_registry.pallet.Error]
    /// 
    ///			Custom [dispatch errors](https://docs.substrate.io/main-docs/build/events-errors/)
    ///			of this pallet.
    ///			
    /// </summary>
    public sealed class EnumError : BaseEnum<Error>
    {
    }
}
