//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace PlutoWallet.NetApiExt.Generated.Model.pallet_staking
{
    
    
    public enum Forcing
    {
        
        NotForcing = 0,
        
        ForceNew = 1,
        
        ForceNone = 2,
        
        ForceAlways = 3,
    }
    
    /// <summary>
    /// >> 498 - Variant[pallet_staking.Forcing]
    /// </summary>
    public sealed class EnumForcing : BaseEnum<Forcing>
    {
    }
}
