//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace Substrate.NetApi.Generated.Model.staging_xcm
{
    
    
    /// <summary>
    /// >> VersionedAssetId
    /// </summary>
    public enum VersionedAssetId
    {
        
        /// <summary>
        /// >> V3
        /// </summary>
        V3 = 3,
    }
    
    /// <summary>
    /// >> 614 - Variant[staging_xcm.VersionedAssetId]
    /// </summary>
    public sealed class EnumVersionedAssetId : BaseEnumExt<VersionedAssetId, BaseVoid, BaseVoid, BaseVoid, Substrate.NetApi.Generated.Model.staging_xcm.v3.multiasset.EnumAssetId>
    {
    }
}
