//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace PlutoWallet.NetApiExt.Generated.Model.polkadot_runtime_parachains.origin.pallet
{
    
    
    public enum Origin
    {
        
        Parachain = 0,
    }
    
    /// <summary>
    /// >> 260 - Variant[polkadot_runtime_parachains.origin.pallet.Origin]
    /// </summary>
    public sealed class EnumOrigin : BaseEnumExt<Origin, PlutoWallet.NetApiExt.Generated.Model.polkadot_parachain.primitives.Id>
    {
    }
}
