//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace PlutoWallet.NetApiExt.Generated.Model.pallet_utility.pallet
{
    
    
    public enum Event
    {
        
        BatchInterrupted = 0,
        
        BatchCompleted = 1,
        
        BatchCompletedWithErrors = 2,
        
        ItemCompleted = 3,
        
        ItemFailed = 4,
        
        DispatchedAs = 5,
    }
    
    /// <summary>
    /// >> 76 - Variant[pallet_utility.pallet.Event]
    /// 
    ///			The [event](https://docs.substrate.io/main-docs/build/events-errors/) emitted
    ///			by this pallet.
    ///			
    /// </summary>
    public sealed class EnumEvent : BaseEnumExt<Event, BaseTuple<Substrate.NetApi.Model.Types.Primitive.U32, PlutoWallet.NetApiExt.Generated.Model.sp_runtime.EnumDispatchError>, BaseVoid, BaseVoid, BaseVoid, PlutoWallet.NetApiExt.Generated.Model.sp_runtime.EnumDispatchError, PlutoWallet.NetApiExt.Generated.Types.Base.EnumResult>
    {
    }
}
