//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace PlutoWallet.NetApiExt.Generated.Model.sp_finality_grandpa
{
    
    
    public enum Equivocation
    {
        
        Prevote = 0,
        
        Precommit = 1,
    }
    
    /// <summary>
    /// >> 218 - Variant[sp_finality_grandpa.Equivocation]
    /// </summary>
    public sealed class EnumEquivocation : BaseEnumExt<Equivocation, PlutoWallet.NetApiExt.Generated.Model.finality_grandpa.EquivocationT1, PlutoWallet.NetApiExt.Generated.Model.finality_grandpa.EquivocationT2>
    {
    }
}
