//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Attributes;
using Ajuna.NetApi.Model.Types.Base;
using Ajuna.NetApi.Model.Types.Metadata.V14;
using System.Collections.Generic;


namespace PlutoWallet.NetApiExt.Generated.Model.polkadot_runtime_parachains.scheduler
{
    
    
    /// <summary>
    /// >> 656 - Composite[polkadot_runtime_parachains.scheduler.QueuedParathread]
    /// </summary>
    [AjunaNodeType(TypeDefEnum.Composite)]
    public sealed class QueuedParathread : BaseType
    {
        
        /// <summary>
        /// >> claim
        /// </summary>
        private PlutoWallet.NetApiExt.Generated.Model.polkadot_primitives.v2.ParathreadEntry _claim;
        
        /// <summary>
        /// >> core_offset
        /// </summary>
        private Ajuna.NetApi.Model.Types.Primitive.U32 _coreOffset;
        
        public PlutoWallet.NetApiExt.Generated.Model.polkadot_primitives.v2.ParathreadEntry Claim
        {
            get
            {
                return this._claim;
            }
            set
            {
                this._claim = value;
            }
        }
        
        public Ajuna.NetApi.Model.Types.Primitive.U32 CoreOffset
        {
            get
            {
                return this._coreOffset;
            }
            set
            {
                this._coreOffset = value;
            }
        }
        
        public override string TypeName()
        {
            return "QueuedParathread";
        }
        
        public override byte[] Encode()
        {
            var result = new List<byte>();
            result.AddRange(Claim.Encode());
            result.AddRange(CoreOffset.Encode());
            return result.ToArray();
        }
        
        public override void Decode(byte[] byteArray, ref int p)
        {
            var start = p;
            Claim = new PlutoWallet.NetApiExt.Generated.Model.polkadot_primitives.v2.ParathreadEntry();
            Claim.Decode(byteArray, ref p);
            CoreOffset = new Ajuna.NetApi.Model.Types.Primitive.U32();
            CoreOffset.Decode(byteArray, ref p);
            TypeSize = p - start;
        }
    }
}
