//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace Bifrost.NetApi.Generated.Model.lend_market.rate_model
{
    
    
    /// <summary>
    /// >> InterestRateModel
    /// </summary>
    public enum InterestRateModel
    {
        
        /// <summary>
        /// >> Jump
        /// </summary>
        Jump = 0,
        
        /// <summary>
        /// >> Curve
        /// </summary>
        Curve = 1,
    }
    
    /// <summary>
    /// >> 377 - Variant[lend_market.rate_model.InterestRateModel]
    /// </summary>
    public sealed class EnumInterestRateModel : BaseEnumExt<InterestRateModel, Bifrost.NetApi.Generated.Model.lend_market.rate_model.JumpModel, Bifrost.NetApi.Generated.Model.lend_market.rate_model.CurveModel>
    {
    }
}
