//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace Polkadot.NetApi.Generated.Model.pallet_asset_rate.pallet
{
    
    
    /// <summary>
    /// >> Event
    /// The `Event` enum of this pallet
    /// </summary>
    public enum Event
    {
        
        /// <summary>
        /// >> AssetRateCreated
        /// </summary>
        AssetRateCreated = 0,
        
        /// <summary>
        /// >> AssetRateRemoved
        /// </summary>
        AssetRateRemoved = 1,
        
        /// <summary>
        /// >> AssetRateUpdated
        /// </summary>
        AssetRateUpdated = 2,
    }
    
    /// <summary>
    /// >> 519 - Variant[pallet_asset_rate.pallet.Event]
    /// The `Event` enum of this pallet
    /// </summary>
    public sealed class EnumEvent : BaseEnumExt<Event, BaseTuple<Polkadot.NetApi.Generated.Model.polkadot_runtime_common.impls.EnumVersionedLocatableAsset, Polkadot.NetApi.Generated.Model.sp_arithmetic.fixed_point.FixedU128>, Polkadot.NetApi.Generated.Model.polkadot_runtime_common.impls.EnumVersionedLocatableAsset, BaseTuple<Polkadot.NetApi.Generated.Model.polkadot_runtime_common.impls.EnumVersionedLocatableAsset, Polkadot.NetApi.Generated.Model.sp_arithmetic.fixed_point.FixedU128, Polkadot.NetApi.Generated.Model.sp_arithmetic.fixed_point.FixedU128>>
    {
    }
}
