//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace Polkadot.NetApi.Generated.Model.pallet_fast_unstake.pallet
{
    
    
    /// <summary>
    /// >> Event
    /// The `Event` enum of this pallet
    /// </summary>
    public enum Event
    {
        
        /// <summary>
        /// >> Unstaked
        /// A staker was unstaked.
        /// </summary>
        Unstaked = 0,
        
        /// <summary>
        /// >> Slashed
        /// A staker was slashed for requesting fast-unstake whilst being exposed.
        /// </summary>
        Slashed = 1,
        
        /// <summary>
        /// >> BatchChecked
        /// A batch was partially checked for the given eras, but the process did not finish.
        /// </summary>
        BatchChecked = 2,
        
        /// <summary>
        /// >> BatchFinished
        /// A batch of a given size was terminated.
        /// 
        /// This is always follows by a number of `Unstaked` or `Slashed` events, marking the end
        /// of the batch. A new batch will be created upon next block.
        /// </summary>
        BatchFinished = 3,
        
        /// <summary>
        /// >> InternalError
        /// An internal error happened. Operations will be paused now.
        /// </summary>
        InternalError = 4,
    }
    
    /// <summary>
    /// >> 498 - Variant[pallet_fast_unstake.pallet.Event]
    /// The `Event` enum of this pallet
    /// </summary>
    public sealed class EnumEvent : BaseEnumExt<Event, BaseTuple<Polkadot.NetApi.Generated.Model.sp_core.crypto.AccountId32, Polkadot.NetApi.Generated.Types.Base.EnumResult>, BaseTuple<Polkadot.NetApi.Generated.Model.sp_core.crypto.AccountId32, Substrate.NetApi.Model.Types.Primitive.U128>, Substrate.NetApi.Model.Types.Base.BaseVec<Substrate.NetApi.Model.Types.Primitive.U32>, Substrate.NetApi.Model.Types.Primitive.U32, BaseVoid>
    {
    }
}
