//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Attributes;
using Substrate.NetApi.Model.Types.Base;
using Substrate.NetApi.Model.Types.Metadata.V14;
using System.Collections.Generic;


namespace Polkadot.NetApi.Generated.Model.polkadot_primitives.v6
{
    
    
    /// <summary>
    /// >> 357 - Composite[polkadot_primitives.v6.DisputeStatementSet]
    /// </summary>
    [SubstrateNodeType(TypeDefEnum.Composite)]
    public sealed class DisputeStatementSet : BaseType
    {
        
        /// <summary>
        /// >> candidate_hash
        /// </summary>
        public Polkadot.NetApi.Generated.Model.polkadot_core_primitives.CandidateHash CandidateHash { get; set; }
        /// <summary>
        /// >> session
        /// </summary>
        public Substrate.NetApi.Model.Types.Primitive.U32 Session { get; set; }
        /// <summary>
        /// >> statements
        /// </summary>
        public Substrate.NetApi.Model.Types.Base.BaseVec<Substrate.NetApi.Model.Types.Base.BaseTuple<Polkadot.NetApi.Generated.Model.polkadot_primitives.v6.EnumDisputeStatement, Polkadot.NetApi.Generated.Model.polkadot_primitives.v6.ValidatorIndex, Polkadot.NetApi.Generated.Model.polkadot_primitives.v6.validator_app.Signature>> Statements { get; set; }
        
        /// <inheritdoc/>
        public override string TypeName()
        {
            return "DisputeStatementSet";
        }
        
        /// <inheritdoc/>
        public override byte[] Encode()
        {
            var result = new List<byte>();
            result.AddRange(CandidateHash.Encode());
            result.AddRange(Session.Encode());
            result.AddRange(Statements.Encode());
            return result.ToArray();
        }
        
        /// <inheritdoc/>
        public override void Decode(byte[] byteArray, ref int p)
        {
            var start = p;
            CandidateHash = new Polkadot.NetApi.Generated.Model.polkadot_core_primitives.CandidateHash();
            CandidateHash.Decode(byteArray, ref p);
            Session = new Substrate.NetApi.Model.Types.Primitive.U32();
            Session.Decode(byteArray, ref p);
            Statements = new Substrate.NetApi.Model.Types.Base.BaseVec<Substrate.NetApi.Model.Types.Base.BaseTuple<Polkadot.NetApi.Generated.Model.polkadot_primitives.v6.EnumDisputeStatement, Polkadot.NetApi.Generated.Model.polkadot_primitives.v6.ValidatorIndex, Polkadot.NetApi.Generated.Model.polkadot_primitives.v6.validator_app.Signature>>();
            Statements.Decode(byteArray, ref p);
            var bytesLength = p - start;
            TypeSize = bytesLength;
            Bytes = new byte[bytesLength];
            System.Array.Copy(byteArray, start, Bytes, 0, bytesLength);
        }
    }
}
