//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace Polkadot.NetApi.Generated.Model.polkadot_primitives.v6
{
    
    
    /// <summary>
    /// >> ValidityAttestation
    /// </summary>
    public enum ValidityAttestation
    {
        
        /// <summary>
        /// >> Implicit
        /// </summary>
        Implicit = 1,
        
        /// <summary>
        /// >> Explicit
        /// </summary>
        Explicit = 2,
    }
    
    /// <summary>
    /// >> 355 - Variant[polkadot_primitives.v6.ValidityAttestation]
    /// </summary>
    public sealed class EnumValidityAttestation : BaseEnumExt<ValidityAttestation, BaseVoid, Polkadot.NetApi.Generated.Model.polkadot_primitives.v6.validator_app.Signature, Polkadot.NetApi.Generated.Model.polkadot_primitives.v6.validator_app.Signature>
    {
    }
}
