//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace Hydration.NetApi.Generated.Model.pallet_staking.pallet
{
    
    
    /// <summary>
    /// >> Call
    /// Contains a variant per dispatchable extrinsic that this pallet has.
    /// </summary>
    public enum Call
    {
        
        /// <summary>
        /// >> initialize_staking
        /// See [`Pallet::initialize_staking`].
        /// </summary>
        initialize_staking = 0,
        
        /// <summary>
        /// >> stake
        /// See [`Pallet::stake`].
        /// </summary>
        stake = 1,
        
        /// <summary>
        /// >> increase_stake
        /// See [`Pallet::increase_stake`].
        /// </summary>
        increase_stake = 2,
        
        /// <summary>
        /// >> claim
        /// See [`Pallet::claim`].
        /// </summary>
        claim = 3,
        
        /// <summary>
        /// >> unstake
        /// See [`Pallet::unstake`].
        /// </summary>
        unstake = 4,
    }
    
    /// <summary>
    /// >> 327 - Variant[pallet_staking.pallet.Call]
    /// Contains a variant per dispatchable extrinsic that this pallet has.
    /// </summary>
    public sealed class EnumCall : BaseEnumExt<Call, BaseVoid, Substrate.NetApi.Model.Types.Primitive.U128, BaseTuple<Substrate.NetApi.Model.Types.Primitive.U128, Substrate.NetApi.Model.Types.Primitive.U128>, Substrate.NetApi.Model.Types.Primitive.U128, Substrate.NetApi.Model.Types.Primitive.U128>
    {
    }
}
