//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.Types.Base;
using System.Collections.Generic;


namespace PlutoWallet.NetApiExt.Generated.Model.polkadot_runtime_parachains.configuration.pallet
{
    
    
    public enum Call
    {
        
        set_validation_upgrade_cooldown = 0,
        
        set_validation_upgrade_delay = 1,
        
        set_code_retention_period = 2,
        
        set_max_code_size = 3,
        
        set_max_pov_size = 4,
        
        set_max_head_data_size = 5,
        
        set_parathread_cores = 6,
        
        set_parathread_retries = 7,
        
        set_group_rotation_frequency = 8,
        
        set_chain_availability_period = 9,
        
        set_thread_availability_period = 10,
        
        set_scheduling_lookahead = 11,
        
        set_max_validators_per_core = 12,
        
        set_max_validators = 13,
        
        set_dispute_period = 14,
        
        set_dispute_post_conclusion_acceptance_period = 15,
        
        set_dispute_max_spam_slots = 16,
        
        set_dispute_conclusion_by_time_out_period = 17,
        
        set_no_show_slots = 18,
        
        set_n_delay_tranches = 19,
        
        set_zeroth_delay_tranche_width = 20,
        
        set_needed_approvals = 21,
        
        set_relay_vrf_modulo_samples = 22,
        
        set_max_upward_queue_count = 23,
        
        set_max_upward_queue_size = 24,
        
        set_max_downward_message_size = 25,
        
        set_ump_service_total_weight = 26,
        
        set_max_upward_message_size = 27,
        
        set_max_upward_message_num_per_candidate = 28,
        
        set_hrmp_open_request_ttl = 29,
        
        set_hrmp_sender_deposit = 30,
        
        set_hrmp_recipient_deposit = 31,
        
        set_hrmp_channel_max_capacity = 32,
        
        set_hrmp_channel_max_total_size = 33,
        
        set_hrmp_max_parachain_inbound_channels = 34,
        
        set_hrmp_max_parathread_inbound_channels = 35,
        
        set_hrmp_channel_max_message_size = 36,
        
        set_hrmp_max_parachain_outbound_channels = 37,
        
        set_hrmp_max_parathread_outbound_channels = 38,
        
        set_hrmp_max_message_num_per_candidate = 39,
        
        set_ump_max_individual_weight = 40,
        
        set_pvf_checking_enabled = 41,
        
        set_pvf_voting_ttl = 42,
        
        set_minimum_validation_upgrade_delay = 43,
        
        set_bypass_consistency_check = 44,
    }
    
    /// <summary>
    /// >> 375 - Variant[polkadot_runtime_parachains.configuration.pallet.Call]
    /// Contains one variant per dispatchable that can be called by an extrinsic.
    /// </summary>
    public sealed class EnumCall : BaseEnumExt<Call, Ajuna.NetApi.Model.Types.Primitive.U32, Ajuna.NetApi.Model.Types.Primitive.U32, Ajuna.NetApi.Model.Types.Primitive.U32, Ajuna.NetApi.Model.Types.Primitive.U32, Ajuna.NetApi.Model.Types.Primitive.U32, Ajuna.NetApi.Model.Types.Primitive.U32, Ajuna.NetApi.Model.Types.Primitive.U32, Ajuna.NetApi.Model.Types.Primitive.U32, Ajuna.NetApi.Model.Types.Primitive.U32, Ajuna.NetApi.Model.Types.Primitive.U32, Ajuna.NetApi.Model.Types.Primitive.U32, Ajuna.NetApi.Model.Types.Primitive.U32, Ajuna.NetApi.Model.Types.Base.BaseOpt<Ajuna.NetApi.Model.Types.Primitive.U32>, Ajuna.NetApi.Model.Types.Base.BaseOpt<Ajuna.NetApi.Model.Types.Primitive.U32>, Ajuna.NetApi.Model.Types.Primitive.U32, Ajuna.NetApi.Model.Types.Primitive.U32, Ajuna.NetApi.Model.Types.Primitive.U32, Ajuna.NetApi.Model.Types.Primitive.U32, Ajuna.NetApi.Model.Types.Primitive.U32, Ajuna.NetApi.Model.Types.Primitive.U32, Ajuna.NetApi.Model.Types.Primitive.U32, Ajuna.NetApi.Model.Types.Primitive.U32, Ajuna.NetApi.Model.Types.Primitive.U32, Ajuna.NetApi.Model.Types.Primitive.U32, Ajuna.NetApi.Model.Types.Primitive.U32, Ajuna.NetApi.Model.Types.Primitive.U32, PlutoWallet.NetApiExt.Generated.Model.sp_weights.weight_v2.Weight, Ajuna.NetApi.Model.Types.Primitive.U32, Ajuna.NetApi.Model.Types.Primitive.U32, Ajuna.NetApi.Model.Types.Primitive.U32, Ajuna.NetApi.Model.Types.Primitive.U128, Ajuna.NetApi.Model.Types.Primitive.U128, Ajuna.NetApi.Model.Types.Primitive.U32, Ajuna.NetApi.Model.Types.Primitive.U32, Ajuna.NetApi.Model.Types.Primitive.U32, Ajuna.NetApi.Model.Types.Primitive.U32, Ajuna.NetApi.Model.Types.Primitive.U32, Ajuna.NetApi.Model.Types.Primitive.U32, Ajuna.NetApi.Model.Types.Primitive.U32, Ajuna.NetApi.Model.Types.Primitive.U32, PlutoWallet.NetApiExt.Generated.Model.sp_weights.weight_v2.Weight, Ajuna.NetApi.Model.Types.Primitive.Bool, Ajuna.NetApi.Model.Types.Primitive.U32, Ajuna.NetApi.Model.Types.Primitive.U32, Ajuna.NetApi.Model.Types.Primitive.Bool>
    {
    }
}
